[package]
name = "mind"
version = "0.1.16"
authors = ["Arijit Basu <sayanarijit@gmail.com>"]
edition = "2018"
description = "A Productive Mind"
license = "MIT"
readme = "README.md"
repository = "https://github.com/sayanarijit/mind"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
dirs = "3.0"
termion = "1.5"
chrono-humanize = "0.0.11"
