[package]
name = "mind"
version = "0.1.4"
authors = ["Arijit Basu <sayanarijit@gmail.com>"]
edition = "2018"
description = "Productive mind"
license = "MIT"
readme = "README.md"
repository = "https://github.com/sayanarijit/mind"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dirs = "3.0"
termion = "1.5"
